### ISSUE TITLE
Wrong seperators on windows when using a Jar file

### ISSUE THREAD

**Issue by BamButz** [axet/lookup#2]
I think there is a problem with seperators when running a jar file on windows.
Maybe im doing something wrong but take look by yourself.

![besalphi](https://cloud.githubusercontent.com/assets/7022144/5599555/55d773f4-92c9-11e4-85d3-7175b0d34d40.png)

**Comment by BamButz** [comment]
Temporary fix

ClassResources.java:

After line 125 append
p = p.replaceAll("\\\\\\\\", "/");

Replace line 137 with
a = StringUtils.removeStart(a, "/");

**Comment by Niro** [comment]
Yes, this is a problem with using lookup with Jars

**Comment by Niro** [comment]
@BamButz I've fixed the problem #9

**Comment by BamButz** [comment]
Good job. Thanks!
